### ISSUE TITLE
Highest hit not cleared per encounter

### ISSUE THREAD

**Issue by aimoaio** [nettyneets/apex-n#1]
![image](https://user-images.githubusercontent.com/5750927/30251419-00fa5ce0-9657-11e7-80ed-4aae300722bd.png)
Hi, there seems to be an issue with clearing the highest hit variable per encounter. As you can see, there is no NIN in this Sophia run (NIN being from a previous dungeon).

**Comment by nyliya** [comment]
Are you able to let me know roughly how much time there was between the two encounters? Did you end the encounter manually (with the button) or let ACT do it after the specified number of seconds?

**Comment by nyliya** [comment]
I have managed to replicate the issue, and I believe it's fixed in the [new release](https://github.com/nettyneets/apex-n/releases/tag/1.2). You only need to replace the apex-n.js file to fix the bug, however I do recommend replacing all of the files as I have made a number of updates today.

However, if the issue persists please let me know - also thank you for bringing this to my attention.

**Comment by aimoaio** [comment]
Awesome, seems to be fixed now! Thanks for responding so quick!
