### ISSUE TITLE
Random resets during battle/inaccurate dps/question about a feature

### ISSUE THREAD

**Issue by Robonatorx** [nettyneets/apex-n#2]
Hello! 
I went ahead and downloaded your skin and i noticed something strange. 
Every now and then during battle the miniparse would randomly reset and stay blank either for a while or until the next battle starts. 

I can not reliably reproduce this issue, but it mostly happens during fights with mechanics. 
For example: I ran around 20 rounds of Bismarck Ex today and during the "downtimes" when we had to dodge stuff etc, the miniparse window would sometimes go blank and stay that way until the end of the battle or until the next fight (against adds for example) starts. 

This also happens randomly during dungeons between trash pulls. 

Sometimes the window would not go blank but fail to display DPS accurately. It would then show me for example do 450dps, when i usually get up to 4k there. Other partymembers would also get weirdly low dps. 

I didn't notice this issue with other skins. 

Any idea what could be causing this? 

Another thing i wanted to ask is: 
Is there a way to not only show the top hit of the entire party but also my personal top hit?

**Comment by nyliya** [comment]
There is an option in ACT under the "Options" tab > "Main table/Encounters" > "General" that reads
`Number of seconds to wait after the last combat action to begin a new encounter`.  This should be adjusted depending on whether you want to parse trash pulls or boss fights.

Mines is set to 45s - this means that if I am in a fight like Emanation (Extreme), the downtime caused by her "mini-cutscene" after the add phase won't cause my ACT to begin a new encounter. This will however lower everyone's dps. (It's damage per second, and there has been a period of no damage dealt meaning the party's dps will be lowered accordingly.)

However, if you enter a dungeon with this setting, you most likely will not have a 45s break between trash pulls, meaning ACT will continue parsing the data into the same encounter. This will also result in your dps decreasing, for the same reason as above.

Depending on whether you want to be able to see a true reflection of your dps per trash pull or be able to upload fights to fflogs you need to adjust this value accordingly. There is nothing I can think of that's in my skin that would affect this as it uses the data that it's passed to it by ACT. Hope that explains it.


As for showing the user's max hit, that's something I could easily add to the skin, only thing is I am not sure where in the overlay to place it.

**Comment by Robonatorx** [comment]
Thanks!
Mine was set to 6 seconds, i doubled that and will see if it helps. 
I personally dont care about FFlogs at all, i am more curious about my performance during the fight.

About the max hit: I'd say just right below the party wide max hit but that would end up looking unbalanced. I can't think of any other useful data to show on the other side though.
